type = "Diamond"
entrypoint = "diamond_yumenikki.dweam_game:YumeNikkiGame"
repo_link = "https://github.com/theoden8/diamond_yumenikki"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.yumenikki]
title = "Yume Nikki"
tags = ["RPG"]
description = "A model of Kikiyama's Yume Nikki, trained on the Shield-Folk world."

[games.yumenikki.buttons]
"â¬†ï¸ Up" = "Arrow Up"
"â¬…ï¸ Left" = "Arrow Left"
"â¬‡ï¸ Down" = "Arrow Down"
"â¡ï¸ Right" = "Arrow Right"
"ğŸ”¨ Interact" = "Z"
"ğŸ”„ Reset" = "Enter"
